server:
  port: 8086
spring:
  application:
    name:
      client-server
  security:
    oauth2:
      client:
        registration:
          client-server-oidc:
            provider: spring
            client-id: client-server
            client-secret: "123456"
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8086/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: client-server-oidc
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9001

